### ISSUE TITLE
View distance is too short

### ISSUE THREAD

**Issue by Bobcheez** [Snoop-Troop-Minecraft-Server/SMP-Server#4]
After the restart today, i don't think the view distance changed at all, i still cant see the ground from about y140, [shown here](https://www.youtube.com/watch?v=pCbBbJ9PWG4)

I set up a test server to see if i could recreate this, and with an in game render distance of 4 i get the same result, [shown here](https://www.youtube.com/watch?v=UEfLQV3i0jo).  I also get the same result if i change "view-distance" to 4 in either server.properties or spigot.yml, though spigot.yml seems to override whatever is set in server.properties if not set to "default".  hopefully this helps at all

**Comment by TA418** [comment]
Hey there thanks for the videos they do help. I'll look into this more. It seemed to be much further out when I checked. I doubled the render distance on the server.

Check your client to make sure you aren't set to 4. I know it may not be the case but it's worth a shot.

I'll keep everyone updated on any changes I find and can implement

**Comment by TA418** [comment]
Issue has been fixed

**Before**
![20220112_093210](https://user-images.githubusercontent.com/16472317/149171367-d5659fb1-a2e2-4474-a3dc-ae541be49509.jpg)

**After**
![20220112_093436](https://user-images.githubusercontent.com/16472317/149171424-2de9e3fe-12cb-4743-937c-8f6dac8d8ad7.jpg)
